# Generated by Django 3.0.5 on 2023-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20230504_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=1200)),
                ('budget', models.IntegerField(choices=[('1', '45000'), ('2', '30000'), ('3', '20000'), ('4', '15000'), ('5', '10000')], default='3')),
                ('date', models.DateField()),
            ],
        ),
    ]
