# Generated by Django 3.0.5 on 2023-05-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
